### ISSUE TITLE
Searching for the right file

### ISSUE THREAD

**Issue by MarBai** [Ludeon/RimWorld-de#11]
Hey, i´ve got one question:

While i was testing, i saw some sentences ingame, which i didnt see in the translation data, but which need correction.

![problem](https://cloud.githubusercontent.com/assets/12127425/7502010/15a679a2-f439-11e4-8fdf-78373299b4f6.png)

does somebody know, where i can find it?

**Comment by HaploX1** [comment]
ThoughtDef -> Thoughts_ConditionsGeneral.xml 
It is in row 31 :)

I use the program dnGREP for this kinds of searches :)
