### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by MarBai** [Ludeon/RimWorld-de#13]
Hi Markus,

the new update is here and i saw, you just worked on it.
If it is ok for you, i will do it like last time.

You will translate the first run and then i watch over it for polishings eventually, ok?

Greetings
Marco

**Comment by HaploX1** [comment]
Hi Marco,

Good to have you still on board :)

You can start your run through the files if you want to. I am finished so far.
If you understands how it works, you can take a look through the TaleDefs, RuleDefs and Strings. Maybe you have an idea how to better the stories. I've done my best so far and will continue to upgrade them whenever I see something, but four eyes see more :)

Thanks for your help so far and as you're still here, I'll add you to the translators if you want me to.

Greetings
Markus

**Comment by HaploX1** [comment]
If you have time, you can take a look at it :-)

**Comment by MarBai** [comment]
Hi Markus,

ive got a question about the work on the german translation.
You know, that there are a lot of files in Rimworld.

Is it possible to see, WHICH files have been changed, when a new update comes out?

This would be much easier to refresh the translation too.
At the moment i have the feeling, i have to look whole the files, but i think, this makes no sense :)
Hopefully you can tell me how to see JUST the CHANGED files.

Greetings :)

**Comment by HaploX1** [comment]
I use the program BeyondCompare to compare the old Core with the new Core files.
Unfortunately BeyondCompare isn't free. But there is WinMerge which does the same functionality. It's not as beautiful, but does the same work for free :-)

**Comment by MarBai** [comment]
Hi Markus,

how youre doing?
im still there and planning to work at the language updates in future. At the moment, i´m very busy with my teacher traineeship, which started in August. I will come back when i can, thats for sure. I think it´s not that bad if there are a few versions between.

Greetings :)

**Comment by HaploX1** [comment]
Take your time..
As there is a bit of idle time until the next release (feb to march 2016?) I don't think you'll have to jump too many versions ;-)
