### ISSUE TITLE
Back in business :)

### ISSUE THREAD

**Issue by MarBai** [Ludeon/RimWorld-de#19]
Hey Markus,

i hope you are well :)

i have much more time now and can continue the translation work on Rimworld.
While watching the new files of Alpha 13, i noticed the new folder structure in the english (core) variation.

Exactly: 
The DefInjected folder was completely changed.
It now only contains just 2 folders (ConceptDef and TraitDef)  instead of 55 before.

Do we have to change this now too in the german translation?
And where are all the files now in the core folders?
They seem gone, for example i cant find the BiomeDef anymore.

It is also possible that it was always like this in the core files and i just didnt notice ;)

Greetings
Marco

**Comment by HaploX1** [comment]
Hi Marco,

Yes, now I'm well again. I've finished the first alpha 13 translation just in time.
As I have privately not as much time as I had last year, I was really happy that I could finish it before the release :)

For your question: The english part doesn't really need to translate anything, as it comes from the defs itself. (And I guess Tynan doesn't like to make work twice). So you need to extract the parts that are needed from the def files themself.

There are a few folder changes in the defs that can't be used in the translation. For example the ThingDefs have folders like ThingDefs_Building. But this can't be used in the tranlsation files as the program doesn't accept that there. So he has the ThingDefs split up in various folders, but we still must throw everything in the ThingDef folder..

If you want, you can try to take a look at the TaleDef and RuleDef. Maybe you'll find a better translation for them as I'm not 100% ok with how it is right now.. But it isn't that easy to understand how it works there :)
But you can test the results ingame in the debug menu. There is a button named Log Tales xxx or something like that to take a look at the resulting tales.
