### ISSUE TITLE
Übersetzung für Recipes_Add.xml

### ISSUE THREAD

**Issue by Giant3** [Ludeon/RimWorld-de#21]
Ich habe jetzt mal ganz schnell die Datei Recipes_Add übersetzt.

LG
Giant
[Recipes_Add.zip](https://github.com/Ludeon/RimWorld-de/files/359581/Recipes_Add.zip)

**Comment by HaploX1** [comment]
Danke, ich hab sie noch etwas angepasst und spiele sie ins main ein :+1: 
Hab tatsächlich vergessen, dass ich die noch nicht übersetzte hatte..
Danke noch einmal :-)

**Comment by Giant3** [comment]
Wollt noch kurz sagen dass in der Recipes_Add.xml ja steht Mace=Keule jedoch in Weapons_Melee.xml steht Mace=Streitkolben, müsste das sann halt noch ändern in der Recipes_Add.xml.
LG
Giant
