### ISSUE TITLE
How to get test version of RimWorld?

### ISSUE THREAD

**Issue by duduluu** [Ludeon/RimWorld-de#30]
Hello, @HaploX1 
Sorry to disturb you.
I’d like to know how to get the test version of Alpha 16, so that we could translate RimWorld in time.

BTW, I developed a CMD tool for translating in C#, I think it could almost perfectly extract translation fields.
The tool: https://github.com/duduluu/RimTrans
And here is the English language data that generated by RimTrans, you might check the match measure: 
https://github.com/RimWorld-zh/RimWorld-English

Have a nice day!

**Comment by HaploX1** [comment]
Hi Duduluu,

Sorry for the delay, but I haven't looked into my mailbox lately..

To get the testversion for translation you need to contact Tynan. 
He can add you to the official translators list and get you access to it.

Greetings
