### ISSUE TITLE
Wall names have an incorrect space.

### ISSUE THREAD

**Issue by JoBa97** [Ludeon/RimWorld-de#39]
e.g. `Granit Wand` or `Holz Wand`. It should be `Granitwand` and `Holzwand` instead, but this does not seem possible since the word for wall and the material names are stored separately.

**Comment by HaploX1** [comment]
Yes I know, also if you write some texts correctly, then they don't really fit to the icons anymore..
So, best is to make a good compromise between correct writing and good looking :)
