### ISSUE TITLE
AnimalProductRaw not "Tierfutter"

### ISSUE THREAD

**Issue by Findus23** [Ludeon/RimWorld-de#41]
Hi, 
Just a small mistranslation I noticed:

The category of food that is produced from Animals shouldn't be called "Tierfutter", but rather "tierische Produkte" or something like this.

https://github.com/Ludeon/RimWorld-de/blob/069642a523b2353831e2bcc48f8e623995030500/DefInjected/ThingCategoryDef/ThingCategories.xml#L13

Thanks for your great translation

**Comment by HaploX1** [comment]
Thanks, I'll correct it.
