### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by ekrempel** [Ludeon/RimWorld-de#57]
The current version of the translation seems not to be compatible to the current version of the game distributed by steam. Is this a known issue?

**Comment by Varisha84** [comment]
What exactly is the issue?

**Comment by ekrempel** [comment]
I just recreated the issue with the stable release:
Deleted the German language files, checked game files by steam (deleted language gets downloaded again). After this the game starts flawlessly.

Now I cloned the latest version from github and replaced the folder "German" with the cloned files. The game now fails to start. It just hangs with a black screen. Attached you can find the log from RimWorld\RimWorldWin64_Data 

[output_log.txt](https://github.com/Ludeon/RimWorld-de/files/2386794/output_log.txt)

**Comment by TeiXeR** [comment]
I'll also check it today in order to find the folders or files which cause the problem.

**Comment by TeiXeR** [comment]
I checked it and Ragnar-F is right. It only works with the unstable version. For the stable release you sadly have to rely on the translation that was available back then.

From my point of view the issue can be closed.

**Comment by HaploX1** [comment]
Closed
