### ISSUE TITLE
Missing dative case

### ISSUE THREAD

**Issue by TeiXeR** [Ludeon/RimWorld-de#59]
Hi everyone,
our translation has many parts where a dative case would've been quite handy. Instead we only have the accusative case.
For example in ..\DefInjected\InteractionDef\Interactions_Romance.xml:

"[INITIATOR_nameDef] kniete nieder und erklärte [RECIPIENT_nameDef], dass [INITIATOR_pronoun] den Rest [INITIATOR_possessive]es Lebens mit [RECIPIENT_objective] verbringen will."

inevitably leads to

"Person1 kniete nieder und erklärte Person2, dass er den Rest seines Lebens mit **sie** verbringen will."

Often we just use [PAWN_nameDef] or [RECIPIENT_nameDef] instead of [...objective] but that does not work all the time (like in the above example).
Does anyone have a suggestion what we could do about it? Is there an easy way to include a dative case (ihm/ihr)? Or should we just replace it with [PAWN_nameDef] or [RECIPIENT_nameDef] everywhere?

**Comment by Ragnar-F** [comment]
Bestimmt kann man auch dort bald so etwas wie `{RECIPIENT_gender ? ihm : ihr}` angeben (https://ludeon.com/forums/index.php?topic=43979.0). Bis dahin bleibt dir nichts anderes übrig, als _objective mit _nameDef zu ersetzen, oder den Satzbau zu ändern, um ihm/ihr zu vermeiden.

Warum bist du der Ansicht, dass _nameDef bei diesem Satz nicht funktioniert? Ich sehe da keine Probleme (außer das es etwas merkwürdig aussieht).

**Comment by TeiXeR** [comment]
{RECIPIENT_gender ? ihm : ihr} looks great. Thanks for the link!

I'll try it when it's ready.
