### ISSUE TITLE
Could Not Resolve Any Root: R_name FirstRulePack: *

### ISSUE THREAD

**Issue by Snackomat** [Ludeon/RimWorld-de#61]
Hey Übersetzungs-Freunde!
Ich habe aktuell das Problem, dass bei der deutschen Übersetzung dieses Problem auftritt. Kann sich das jemand mal ansehen?

BR

**Comment by TeiXeR** [comment]
Hey Snackomat,
an welcher Stelle macht sich das Problem denn genau bemerkbar?

**Comment by TeiXeR** [comment]
Ich würde diesen "Issue" dann Anfang nächster Woche schließen. So bleibt noch ein bisschen Zeit, um mehr auf die Details einzugehen.
Ansonsten würde ich allgemein raten, die deutschen Sprachdateien aus Steam einfach mal komplett durch die aktuelle Version von GitHub zu ersetzen. Eventuell sind da einfach ein paar Dateien verlorengegangen.
