### ISSUE TITLE
GrammarResolver failed to resolve a text (rootKeyword: r_logentry)

### ISSUE THREAD

**Issue by Endgegner** [Ludeon/RimWorld-de#62]
GrammarResolver failed to resolve a text (rootKeyword: r_logentry)
Custom rules:
  INITIATOR_nameFull->Goemo 'Geier' Izo
  INITIATOR_label->Geier
  INITIATOR_definite->Geier
  INITIATOR_nameDef->Geier
  INITIATOR_indefinite->Geier
  INITIATOR_nameIndef->Geier
  INITIATOR_pronoun->er
  INITIATOR_possessive->sein
  INITIATOR_objective->ihn
  INITIATOR_factionName->Neuer Stamm
  INITIATOR_kind->Stammesmitglied
  INITIATOR_title->Höhlenhüter
  WEAPON_label->Firecracker
  WEAPON_definite->der Firecracker
  WEAPON_indefinite->ein Firecracker
  WEAPON_possessive->sein
  WEAPON_projectile_label->Microexplosion
  WEAPON_projectile_definite->der Microexplosion
  WEAPON_projectile_indefinite->ein Microexplosion
  WEAPON_projectile_possessive->sein

Includes:
  Combat_RangedFire_Thrown

Constants:
  INITIATOR_flesh: Normal
  RECIPIENT_missing: True
  BURST: False

0 ->[r_logentry] 
1    r_logentry->[INITIATOR_label] [threw] [INITIATOR_possessive] [WEAPON_projectile_label] auf [RECIPIENT_label]. 
2       INITIATOR_label->Geier 
2       threw->[verb_threw] 
3          verb_threw->schmiss 
2       INITIATOR_possessive->sein 
2       WEAPON_projectile_label->Microexplosion UNRESOLVABLE: Cannot resolve subsymbol 'RECIPIENT_label'
1    r_logentry->[INITIATOR_label] [threw_a] [WEAPON_projectile_label] auf [RECIPIENT_label]. 
2       INITIATOR_label->Geier 
2       threw_a->[adverb_threw] [verb_threw] ein 
3          adverb_threw->sorgfältig 
3          verb_threw->schmiss 
2       WEAPON_projectile_label->Microexplosion UNRESOLVABLE: Cannot resolve subsymbol 'RECIPIENT_label'UNRESOLVABLE: Cannot resolve subsymbol 'r_logentry'
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Verse.Grammar.GrammarResolver:ResolveUnsafe(String, GrammarRequest, Boolean&, String, Boolean, Boolean)
Verse.Grammar.GrammarResolver:ResolveUnsafe(String, GrammarRequest, String, Boolean, Boolean)
Verse.Grammar.GrammarResolver:ResolveUnsafe(String, GrammarRequest, Boolean&, String, Boolean, Boolean)
Verse.Grammar.GrammarResolver:Resolve(String, GrammarRequest, String, Boolean, String)
Verse.LogEntry:ToGameStringFromPOV_Worker(Thing, Boolean)
Verse.LogEntry:ToGameStringFromPOV(Thing, Boolean)
Verse.LogEntry:GetTextHeight(Thing, Single)
RimWorld.LogLineDisplayableLog:GetHeight_Worker(Single)
RimWorld.LogLineDisplayable:GetHeight(Single)
RimWorld.ITab_Pawn_Log:FillTab()
Verse.<DoTabGUI>c__AnonStorey0:<>m__0()
Verse.ImmediateWindow:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

Occured on trying to look at death reasons (only in german, swapping to english fixes the problem)

Kind Regards

**Comment by TeiXeR** [comment]
INITIATOR_label->Geier
RECIPIENT_label->"UNBEKANNT"
Aus irgendeinem Grund kann der Getroffene nicht angegeben werden.

Hmm, das könnte Mod-Problem sein. Wer/Was war denn der Getroffene? War es eine Kreatur, die es nicht in der Vanilla-Version gibt? Oder hatte die Kreatur einen Namen mit Sonderzeichen, die es im Deutschen nicht gibt?
