### ISSUE TITLE
Vorschlag für Aufzählungen

### ISSUE THREAD

**Issue by TeiXeR** [Ludeon/RimWorld-de#66]
Ich finde, die Aufzählungen bei Questbeschreibungen oder -belohnungen können manchmal sehr schwer/hässlich zu lesen sein, da sie sich als reine Textblöcke präsentieren. Je mehr Unterpunkte dazukommen oder je länger diese werden, umso schlimmer.
Daher hier ein Vorschlag, wie man das vielleicht etwas eingängiger gestalten könnte.

Beispiel:
Vorher: "Wenn das passiert wird erstens dem Kolonisten, der die Quest annimmt, 5 königliche Gunst gewährt, zweitens ein Geschenk via Transportkapseln gebracht, und drittens noch etwas anderes passieren."

Nachher: "Wenn das passiert wird 
1) dem Kolonisten, der die Quest annimmt, 5 königliche Gunst gewährt, 
2) ein Geschenk via Transportkapseln gebracht, und 
3) noch etwas anderes passieren."

So, finde ich, kommt man ein bisschen strukturierter an die wichtigen Informationen ran, ohne dabei die Grammatik kaputtzumachen.

"Erstens", "zweitens" usw. wurden ersetzt, da diese sonst bei einem Zeilenumbruch automatisch großgeschrieben werden. Sobald man Punkte schreibt, passiert das Gleiche.

Wie sind eure Meinungen dazu?

**Comment by HaploX1** [comment]
Hi TeiXeR,
von meiner Seite her spricht nichts dagegen. Ich weiß nur gerade nicht, wie aufwändig die Implementierung wäre, aber wenn wir das so hinbekommen, warum nicht?
Nur drauf achten, dass nach der Implementierung auch alle Quests so aussehen wie gewünscht und es keine unangenehmen Nebeneffekte gibt. -> Tests mit 10-20 Quests (ist via Debug-Mode ja relativ schnell passiert)

**Comment by TeiXeR** [comment]
Ich habe gerade gemerkt, dass mein Text bei Git ein wenig verändert wurde. So müsste das eigentlich aussehen:

Nachher: "Wenn das passiert wird 
1 ) dem Kolonisten, der die Quest annimmt, 5 königliche Gunst gewährt, 
2 ) ein Geschenk via Transportkapseln gebracht, und 
3 ) noch etwas anderes passieren."

Also 'Klammer zu' statt 'Punkt' und ohne Leerzeichen vor der Klammer. Nach Punkten wird ja auch großgeschrieben, daher sollten wir die eher vermeiden.

**Comment by Ragnar-F** [comment]
Ich habe auch nichts dagegen.
