### ISSUE TITLE
Grammatikfehler im Start Screen

### ISSUE THREAD

**Issue by fastrockstar** [Ludeon/RimWorld-de#70]
Alle Übersetzungen von RimWorld sind von Fans erstellt _wurden_ statt _worden_

**Comment by TeiXeR** [comment]
Danke.
Ist nun behoben.

**Comment by Ragnar-F** [comment]
Warum ist das ein Grammatikfehler? Entweder heißt es "wurden von X erstellt" (Präteritum) oder "sind von X erstellt worden" (Perfekt).
