### ISSUE TITLE
Stufenbereich beim Drogenlabor kann nicht eingestellt werden

### ISSUE THREAD

**Issue by wzurborg** [Ludeon/RimWorld-de#74]
Die Länge des kombinierten Strings verdrängt den Stufenbereichsregler. Wenn man "Stufenbereich" durch "Level" ersetzt, passt es. Falls es dagegen keine Einwände gibt, kann ich das hochladen.

![Jetzt](https://snipboard.io/owYBiN.jpg) ![Neu](https://snipboard.io/KTeDcr.jpg)

Ich habe nicht alle Bills daraufhin untersucht!

**Comment by TeiXeR** [comment]
Sehr guter Fund!
Wandle es bitte in "Erlaubte Stufe" um. 
"Level" zu benutzen, wäre hier mein einziger Einwand, da hierbei sonst auch immer "Stufe" benutzt wird.

**Comment by wzurborg** [comment]
ok
