### ISSUE TITLE
Da gehen die Nerven mit sie durch ...

### ISSUE THREAD

**Issue by wzurborg** [Ludeon/RimWorld-de#76]
![grafik](https://user-images.githubusercontent.com/1320950/114450993-017a5380-9bd7-11eb-9ceb-2ffd4413aef1.png)

1. Die Nerven gehen jemandem durch, nicht **mit** jemandem.
2. Schöner Dativ! Hier gibt es eine gute Möglichkeit der Umschreibung.
3. "andere" wird hier kleingeschrieben.

Vorschlag:
![grafik](https://user-images.githubusercontent.com/1320950/114451421-81082280-9bd7-11eb-8edd-82df7f77cc06.png)

**Comment by Ragnar-F** [comment]
Danke. Nur zur Info: Wenn du ihm/ihr in einem Text brauchst, kannst du sowas wie `{PAWN_gender ? ihm : ihr}` angeben.
